apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-config
data:
  indy_config.py: |-
    # Current network
    NETWORK_NAME = '{{ .Values.network_name }}'

    # Disable stdout logging
    enableStdOutLogging = False

    # Directory to store ledger.
    LEDGER_DIR = '/var/lib/indy'

    # Directory to store logs.
    LOG_DIR = '/var/log/indy'

    # Directory to store keys.
    KEYS_DIR = '/var/lib/indy'

    # Directory to store genesis transactions files.
    GENESIS_DIR = '/var/lib/indy'

    # Directory to store backups.
    BACKUP_DIR = '/var/lib/indy/backup'

    # Directory to store plugins.
    PLUGINS_DIR = '/var/lib/indy/plugins'

    # Directory to store node info.
    NODE_INFO_DIR = '/var/lib/indy'
  {{- range $node := .Values.nodes }}
  indy.env-{{ $node.alias }}: |-
    NODE_NAME={{ $node.alias }}
    NODE_IP=0.0.0.0
    NODE_PORT={{ $node.node_port }}
    NODE_CLIENT_IP=0.0.0.0
    NODE_CLIENT_PORT={{  $node.client_port }}
    CLIENT_CONNECTIONS_LIMIT=500
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-node-cm-genesis
data:
  domain_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"alias":"trustee1","dest":"6zLSG6qzLw8cpBinSmfBtp","role":"0","verkey":"4GJww21vYedaNNS1eW9c2Zv3px8yiBXFanKxPnGahBfE"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee2","dest":"4ZSHHpspZfkeo3153YnAxb","role":"0","verkey":"2wWr1hbKNThn4tSqWLa9TzjobbasWthRMZckR84qJp4h"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee3","dest":"6Yed1bGmQSsj3ifr3N8bTv","role":"0","verkey":"42JwxGsP2dQkRhXUFmkZs8jQanUrrpv7fTqR1VsJx7yB"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee4","dest":"SmZtS2Y49U7eSRoCcAN5uF","role":"0","verkey":"F3bDAFr1XojjA2ZTh9C4Z2Caorji7toawfoKnqSCSF7i"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee5","dest":"FvbL1tTfteH8Kppq3gqDFS","role":"0","verkey":"98n4myhYozZZpJTKGPBs9YgMxrqz7JfrEHustUenhzVd"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"8dY7tV7uVKcLkMZX5WmEY9","role":"2","verkey":"5ACTDyAj6x9i5zCLhX7Fr4mqJJbHtBqYd4XVD5po3o7E"},"metadata":{"from":"FvbL1tTfteH8Kppq3gqDFS"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"CtMSvArBSvjTD2DiLxRUKf","role":"2","verkey":"7UinxzrAwHedKe6ZicUy7qwDMnj4BJ12ysNiGeYDqUxo"},"metadata":{"from":"FvbL1tTfteH8Kppq3gqDFS"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"V9R318AgGPUWo3H7hD7xEb","role":"2","verkey":"GLiqYSfLxvYoYoLzVou84d7fehmjub6UVtTGKQPe2DvH"},"metadata":{"from":"FvbL1tTfteH8Kppq3gqDFS"},"type":"1"},"txnMetadata":{"seqNo":8},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"NdXDMg8YuHLv56i52pu9SG","role":"2","verkey":"CnkszoyFMcKtcg4FLnZdPbSuVZvSA5eCa6TW35gEuAEH"},"metadata":{"from":"FvbL1tTfteH8Kppq3gqDFS"},"type":"1"},"txnMetadata":{"seqNo":9},"ver":"1"}

  pool_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward1","blskey":"4PmB2arSdS1DQPAAxe6JBLNucHwaoocQba9voLw8pAfYv4KQzs6HAd451Q7LpHWiPns2BytY4sCEU6jLjWJ1fDhhU7jzhYVAZy4hKrpQNqh4swaCdHtPovrAHiUdpoW6fCwCpZxx121Yj3yi4vHk8N8G8j4d1cXWkS9duNTvuprjNjj","blskey_pop":"QzUsmaTxWnHLnLaBkTG4Ms7sfWNBbfthv8KRjuSpTScFpzT1Yomc3t425NwzxwFZrbDXSzV6ss44GzAQuPuJ4jtr1g3W9nvXHuBve1Za4GzDWAkvsdAcJUhkCP7tN852KLUSkfgZbeXGspBDkVBo5Y63YZ44nWZH5MX5Z5Aa5Zkwwu","client_ip":"steward1.default.svc.cluster.local","client_port":"steward1_9702","node_ip":"steward1.default.svc.cluster.local","node_port":"steward1_9701","services":["VALIDATOR"]},"dest":"GqVaKvrFEvyj5ETuupoVoVm3GyjyrKH6xn3qNTg8yqgC"},"metadata":{"from":"8dY7tV7uVKcLkMZX5WmEY9"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"d217afd29dd422162e5c528f3fd023397c8469b9e3f00f46835d0e671006f50b"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward2","blskey":"dbk5ym7XxWfFM76EyPDkT3CV3yvXpStvg5JbkD1NRPcbSTFbeaqEV2xqRbU1yDtTcNwGAtTNKYyzbUz6ACNaBEpd5jxCBQvuekEwVZwS1jMkLwCvrPxt1HYwJc19WpdfoKjPgPYNwMtXMuz6FHSzKPoqkkXymwqdvRdiyFrANbF9XQ","blskey_pop":"R9NxtpMWsmScWNUCURShzjyxZzLNUHrkELvijpVY9JLwh8GEGBqAwPGsuWFaEFwNK4MjDUxtt8BicgpK3bYD9e6RQEjJPJjy9azR3rVWjZceQZwCBNZCnVGGPuMFhsR4CvjgmaQ7xVZWXREUCcQqAmdyyFyUufL9Wkwhi5WSTDUsEF","client_ip":"steward2.default.svc.cluster.local","client_port":"steward2_9702","node_ip":"steward2.default.svc.cluster.local","node_port":"steward2_9701","services":["VALIDATOR"]},"dest":"FZyn2i3oeWjWtSXTJtcXcwa9GLa4ipahTMpGkso55DrQ"},"metadata":{"from":"CtMSvArBSvjTD2DiLxRUKf"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"b69e5fbf21173123d5733231a5e1cbcf53233f2ed08695daefab12dca9092114"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward3","blskey":"4JZJbx3SMtB4jfo32LfwrqnbuZxqUHaCVPZZQB3TSCkBqwtuHc4PcTBFfthUXRpMJrXUqUMFbZC2tNtCdMqasB9EtEqeW8HRvcpHyiX4rhvNQXxzfGfVqw7cpWAKUd3jzDuaUD8ti96eKkwwVTUf2z56yYjHByiSHS5J6Dg4da5q5Rd","blskey_pop":"RL4ftUsWb21AXfka49RkxRci6xSSzysmJZGKhEg3cxXXCi3Nqoq45w9XFKEzY69RzDH7KGrzCLWsYYWvjeuPsnaC79P1DiwEqAs4gg4mivTTtRbfNcGAREwBWEViRBa4W74sL513xi4L3X61S6SS58imdZh6JJPYHx2qSuoTvNdS9V","client_ip":"steward3.default.svc.cluster.local","client_port":"steward3_9702","node_ip":"steward3.default.svc.cluster.local","node_port":"steward3_9701","services":["VALIDATOR"]},"dest":"4t96sapkLMQHeWue4TQbQzN1ZmkR5GhSpfcdj8NPDy7p"},"metadata":{"from":"V9R318AgGPUWo3H7hD7xEb"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"f05151122ea0c4c8bdea1ed2bae305bb37934a0c92a566a627abb1d1c9778b9f"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward4","blskey":"gr3ayYySeFrBKyvVDhvFeA8fPWnBnMWcTaCyVCH8qAgkku9ZJpeT2qyghLtyNbsvVbibVmZN81fCnx5oASy64mk3zN5QE9wn7iWmGL1htRQmZV5KTJC1vjQhmSB6LwG1UBPaDnQ7y9n6MKC26E9kdCf3KYyXaaxxAide2vg8oBGYPh","blskey_pop":"RQRNGuD6DQVXPKJqU2KvEojDRCmLQBK4HCmHJw9Ys3oMnwrz9hy3Hik5mvL9iDiMXFPgZn5HNGrRz5H25WGUtyFV5o4oarQXVDuV72ymYgaUwEfp6TxP6Hp2Yfkbr4brpW4xKPKAkHbJv39sHBTnAipkQvRDaFQmZJNVgMqj8rKDGj","client_ip":"steward4.default.svc.cluster.local","client_port":"steward4_9702","node_ip":"steward4.default.svc.cluster.local","node_port":"steward4_9701","services":["VALIDATOR"]},"dest":"BPGQXdqqvCd1655EaDRhEW5w6pMMwLQmWpNCKqVtN4YK"},"metadata":{"from":"NdXDMg8YuHLv56i52pu9SG"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"34569ec776a6f8cf766aece248c78fd21f652a08f3f44daae23c9cbc07623601"},"ver":"1"}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  entrypoint.sh: |-
    #!/bin/sh
    {{ if .Release.IsInstall }}
    init_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT > /extdata/$node
    {{ end }}
    
    {{ if .Release.IsUpgrade }}
    cp /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis
    cp /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis
    
    {{- range $inter_node := .Values.nodes }}
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9702/s//${{ upper $inter_node.alias }}_SERVICE_PORT_CLIENT/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9701/s//${{ upper $inter_node.alias }}_SERVICE_PORT_NODE/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    {{- end }}
    start_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT &
    {{ end }}

    sh -c tail -f /dev/null