apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-config
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  indy_config.py: |-
    # Current network
    NETWORK_NAME = '{{ .Values.network_name }}'

    # Disable stdout logging
    enableStdOutLogging = False

    # Directory to store ledger.
    LEDGER_DIR = '/var/lib/indy'

    # Directory to store logs.
    LOG_DIR = '/var/log/indy'

    # Directory to store keys.
    KEYS_DIR = '/var/lib/indy'

    # Directory to store genesis transactions files.
    GENESIS_DIR = '/var/lib/indy'

    # Directory to store backups.
    BACKUP_DIR = '/var/lib/indy/backup'

    # Directory to store plugins.
    PLUGINS_DIR = '/var/lib/indy/plugins'

    # Directory to store node info.
    NODE_INFO_DIR = '/var/lib/indy'
  {{- range $node := .Values.nodes }}
  indy.env-{{ $node.alias }}: |-
    NODE_NAME={{ $node.alias }}
    NODE_IP=0.0.0.0
    NODE_PORT={{ $node.node_port }}
    NODE_CLIENT_IP=0.0.0.0
    NODE_CLIENT_PORT={{  $node.client_port }}
    CLIENT_CONNECTIONS_LIMIT=500
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-node-cm-genesis
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  domain_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"alias":"trustee1","dest":"QJna9e3Z7XJfG6xwxVLd3V","role":"0","verkey":"DhmcTgBVDmEqveQXHKhdonzbMkCBRd1hzMegsSPVFkNg"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee2","dest":"WU2KG6TQ8BC93Gaekkg7hC","role":"0","verkey":"H4UaPkNv91oDgFVsN67Bj8Vhqd9LFNVVEZXUGjpU1Wrz"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee3","dest":"Gi4DsiqvmE2cBsNWA4TYvm","role":"0","verkey":"9ZZGCRzCoYCTL7GwNQYUHV1piXF6KxR7k366ww2X5rZh"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee4","dest":"8hTDeDWoZzUmJJKForQj5B","role":"0","verkey":"5CLEH5YiHoH71zMHH3LB6QEAY3j43WagzvPDgZrSsCVN"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee5","dest":"BjrrAwR9oTA8gnqgKiGzJT","role":"0","verkey":"6rUpGTAAxChMdYUvzCHkqAvQi9757oCQNUTPFkmidgRY"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"VZjXNStoQdJEushNrAhMSs","role":"2","verkey":"GZybtDimi7q8CouDZdhAGUsayQeJNmSh1HmCPrpxtZxC"},"metadata":{"from":"BjrrAwR9oTA8gnqgKiGzJT"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"B8B2VE9hTEdp4wAfVmu1tp","role":"2","verkey":"6X2h7Fj8MDsTqp1umYMmSj2rn97xcb9tavZuRY7rckAg"},"metadata":{"from":"BjrrAwR9oTA8gnqgKiGzJT"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"Hr4LRqh71FHH5egdb2zeGV","role":"2","verkey":"ABXiPwhvSbVfX7txA7SmaL79UCiKrxMBQJkm4dRSRrEC"},"metadata":{"from":"BjrrAwR9oTA8gnqgKiGzJT"},"type":"1"},"txnMetadata":{"seqNo":8},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"Rgeurm8D1nBzaQFUGDhXPo","role":"2","verkey":"ETJPrW3X8xuBq4fmqJQoQzwgYhgsWey6foVhgNwGTYRk"},"metadata":{"from":"BjrrAwR9oTA8gnqgKiGzJT"},"type":"1"},"txnMetadata":{"seqNo":9},"ver":"1"}

  pool_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward1","blskey":"3quq457bgwEDUryQG5wVk6BzKg8X4DFuU1yhoJpsYpLCf3n7G2FQdj9zqoecZavoGzsZJDydruzPWnnCWdzN1f1JkZ5gm8njoBHxcxLjZEJApi8RTHdMWoTEgPSrY6cwQ8HY8jUNoBrzuFmJZqNrWypGfTzJncwZ4s65biYZuhSmaWR","blskey_pop":"Qos8ctvSKWzDoHnb8xS2DLoB9y5PFPQ38bdXhzqLsmMbGX3swZ1gYo9U28yyZvVvoYRLDdqyGpjWY51eSe4z4RHf2QY3ekGKMZPwrAThUsZErYSZzDPmXaQmTYvDPTxBeH1PGAygay581xvZmayqeTGBvHiW41Nz9nrpiwVyEBov3h","client_ip":"steward1.default.svc.cluster.local","client_port":"steward1_9702","node_ip":"steward1.default.svc.cluster.local","node_port":"steward1_9701","services":["VALIDATOR"]},"dest":"9HrKdNjBkzsZMGEW96ekDGyneZPTm2nJN84a8vHvu38L"},"metadata":{"from":"VZjXNStoQdJEushNrAhMSs"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"d217afd29dd422162e5c528f3fd023397c8469b9e3f00f46835d0e671006f50b"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward2","blskey":"4JTCzdvW1NWrNjUAcjeYrFLwk4DJ4nWhaPpA5o1PQgHgVqhPGnUG2XdRiFp6bVSKvFyxfLNu8jZBe5C1BVmA9wo7C16tNSidYfNMnfXX6kiqcZrjTo83cfvb3U2rEvEP7hnBaUmWArgpR3kRMFU1sCdY537SVrtqq2gPnSVEjPFjzr2","blskey_pop":"R9PPGkGhBkNKQYKATF2neET4VxrUUPVHLc6uu3QWJF6nDCR4tt76Vv8j6yFcJ6SqLFLcqqcY79qaF44WF73T1Lf5GUPZ4KR3SeuhfkmTe4RU2RjaU6NYfxiNW9gwxhBPkX31AZiN1nxxynu7zUaQfVqCLKKF5eSPhiXGeNYjgzNPWX","client_ip":"steward2.default.svc.cluster.local","client_port":"steward2_9702","node_ip":"steward2.default.svc.cluster.local","node_port":"steward2_9701","services":["VALIDATOR"]},"dest":"6jBCgJz3opRqfRmonoHooUcbd2cgQwrDrhnvGFae2Q7X"},"metadata":{"from":"B8B2VE9hTEdp4wAfVmu1tp"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"b69e5fbf21173123d5733231a5e1cbcf53233f2ed08695daefab12dca9092114"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward3","blskey":"4G997ueEsQDkpXteKKszsdT6ezbCCHzRw8YVrf7PxyzSu6JDC4zgcaGw7m6Va3oWJLeoAaV7hJAhRpa8h3wMN2GLhdhFyXHsAtwQSY5pEAKefHdFc3AoDWUybzxFq8gtXZu2DGmd1HUaVbcwrDQ1fHiWJUUX2iJN4F5QFFssP7n3aSn","blskey_pop":"RQv4pFzCCQjDPVR8EvNy7VYrsefQoBLurZpoExThH6nKjBCdgLpsv3qodhkp4JYGbag1EtkQ3i5dYoSxLAbcese6oFPdh2N6kEaSSYZQdcyjmhhranPmTesCbnV723QH5LSkWv8VBW7PNbu3GkATd6EaTYgeeMF22YWGbDaWusAqeP","client_ip":"steward3.default.svc.cluster.local","client_port":"steward3_9702","node_ip":"steward3.default.svc.cluster.local","node_port":"steward3_9701","services":["VALIDATOR"]},"dest":"E3xcR7iPqvsHvQdEPTPm1PgHjsMHLJ6fpJQywpdHNYJi"},"metadata":{"from":"Hr4LRqh71FHH5egdb2zeGV"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"f05151122ea0c4c8bdea1ed2bae305bb37934a0c92a566a627abb1d1c9778b9f"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward4","blskey":"38widz9PAvVCWmQa65p4HM5q5KH2sosGxNvctwYmwr2pURaZeRGjD7n6c6SfzXegSd2jGweDP4JNKeB3dk4mksF3Ch3Woe7jJuZYn1g5BiwYnNcywSNVoRJSGv4nWuKhDd69J4Rgq4kge7oWQLBTzU5cqYxUa1fasKu4HQDmJjNiMqV","blskey_pop":"RHsn1Notav3dR8rUGnuPzCAs1vWJtNQaw52mmWEGK79KXg1ULDQUBFvX2NgH5tVkTHJw9dqYfTHRXDEMAVZMQpsAbYYkJo6hUCbrRRD4Tix6bJby1MDXAh3Brc9zmA6jotCrnZjaAeLuVGGWUMWgQ9LV4NJ37kbP6J6d598ZrKMi9D","client_ip":"steward4.default.svc.cluster.local","client_port":"steward4_9702","node_ip":"steward4.default.svc.cluster.local","node_port":"steward4_9701","services":["VALIDATOR"]},"dest":"BTVGrEiaJyrw5xR5soU3UfTh1dPv7upcQn2yJrBxtr3W"},"metadata":{"from":"Rgeurm8D1nBzaQFUGDhXPo"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"34569ec776a6f8cf766aece248c78fd21f652a08f3f44daae23c9cbc07623601"},"ver":"1"}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  entrypoint.sh: |-
    #!/bin/sh
    {{ if .Release.IsInstall }}
    init_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT > /extdata/$node
    {{ end }}
    
    {{ if .Release.IsUpgrade }}
    cp /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis
    cp /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis
    
    {{- range $inter_node := .Values.nodes }}
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9702/s//${{ upper $inter_node.alias }}_SERVICE_PORT_CLIENT/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9701/s//${{ upper $inter_node.alias }}_SERVICE_PORT_NODE/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    {{- end }}
    start_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT &
    {{ end }}