apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-config
data:
  indy_config.py: |-
    # Current network
    NETWORK_NAME = '{{ .Values.network_name }}'

    # Disable stdout logging
    enableStdOutLogging = False

    # Directory to store ledger.
    LEDGER_DIR = '/var/lib/indy'

    # Directory to store logs.
    LOG_DIR = '/var/log/indy'

    # Directory to store keys.
    KEYS_DIR = '/var/lib/indy'

    # Directory to store genesis transactions files.
    GENESIS_DIR = '/var/lib/indy'

    # Directory to store backups.
    BACKUP_DIR = '/var/lib/indy/backup'

    # Directory to store plugins.
    PLUGINS_DIR = '/var/lib/indy/plugins'

    # Directory to store node info.
    NODE_INFO_DIR = '/var/lib/indy'
  {{- range $node := .Values.nodes }}
  indy.env-{{ $node.alias }}: |-
    NODE_NAME={{ $node.alias }}
    NODE_IP=0.0.0.0
    NODE_PORT={{ $node.node_port }}
    NODE_CLIENT_IP=0.0.0.0
    NODE_CLIENT_PORT={{  $node.client_port }}
    CLIENT_CONNECTIONS_LIMIT=500
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-node-cm-genesis
data:
  domain_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"alias":"trustee1","dest":"XiAc84RmYc1hgG54g2hNQU","role":"0","verkey":"HjoA56MqqTLVNmshHzSFmtpWGfY76g9y17eTbsM8yYfU"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee2","dest":"BdqcqdHxHTYX5rhCtSkfQu","role":"0","verkey":"6oCURSnf3eTsmuGtZxWKJibcoEJSszVAqH3ZLVVCUWpZ"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee3","dest":"QgzVfuydEp3i7ESM1XMvoc","role":"0","verkey":"DusaEpxcCroM2W1cxYXQn7xRryGWm7hPbHBgkZhGPCNt"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee4","dest":"LEr7WXmjLZsnYsjqq5TmyR","role":"0","verkey":"BVB7iz7fCwYWNrKqHurLFd9guzBsRnvtH1Uj3sAGthZq"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee5","dest":"JyiBmuSfoiwqucAK7fCJL2","role":"0","verkey":"AoK84pYWmvtsSVqNGT199yhV8gMHFc6DXFQEQRuFy1Rj"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"RHonipXs1Pq3m7WSXwT8r9","role":"2","verkey":"EErA6tV2gcBjFEyityf9GCpcLJLQgiguYDJZ2dvrhS9x"},"metadata":{"from":"JyiBmuSfoiwqucAK7fCJL2"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"WLEgXx1KzroBMAwFpvvcWx","role":"2","verkey":"GzERNoKNgdC7Bju6MYNDuFNUH4aFMaDuQaXBUvhBG7Au"},"metadata":{"from":"JyiBmuSfoiwqucAK7fCJL2"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"BNYqB16U6ELbSxpUqYGxu6","role":"2","verkey":"6es9KsPkJFBnVB8jXQ6bZzhiXVDBZtsvPhUVwjn8wnmF"},"metadata":{"from":"JyiBmuSfoiwqucAK7fCJL2"},"type":"1"},"txnMetadata":{"seqNo":8},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"QUUJicdurEobs2wHs2CJum","role":"2","verkey":"Do3mygDjj3tTzXPFknaMoW29s1FPaeS5dyVBgkRTuM8F"},"metadata":{"from":"JyiBmuSfoiwqucAK7fCJL2"},"type":"1"},"txnMetadata":{"seqNo":9},"ver":"1"}

  pool_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward1","blskey":"3eYZvr8M6FUxvoHjsohNbcWFpnHi6HW9eh5ZJ2rw2FcVGjYz1PnxDWdrHi1sp3pFASem1zgPp8zkQrSDUmG9NzJGRyEkJwr3aUA61bM8ioCDzQL7FCjThq1UaJUpirymb4PHQEPL1xNBsVtfg5zLNzBZkRGKv6MwtdgyGkyebw1ZrZg","blskey_pop":"QxM5T3nLfST1ToVy8BHo9tMHjTRkFW7XNFpmjjoWkWu8jvWPJFssgCNHi4AnBgkbe5KDA86ywuLrhwtNDeKTr6rXTatWYHp217BcbzXvm9p9sN1Gc9CnW3vDtU77euGheVZeMop6vi2XwfbHCesGjGVDzAnEpZgCvwZzDRJAhy9jtB","client_ip":"steward1.default.svc.cluster.local","client_port":"steward1_9702","node_ip":"steward1.default.svc.cluster.local","node_port":"steward1_9701","services":["VALIDATOR"]},"dest":"2nVWqdVLGaG58DCcJYLq2GsLaJtkye4QzgNQ58HSfZgy"},"metadata":{"from":"RHonipXs1Pq3m7WSXwT8r9"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"d217afd29dd422162e5c528f3fd023397c8469b9e3f00f46835d0e671006f50b"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward2","blskey":"2vc7sobGXzGPYQ2zRSKx9NtcgKv4fuNiwYJCkHDgec7o6D6jobP4eSKhnEibSk4WHd7Kp9hvKoh8QvHDZSCXwqNwhGBW12ajfiouukLABrenQoFixMsA6tCpc1h13aWyq3dC9FMRNA34r5geAX7B7zC427qiZp9GponiQD7Fn7BihqU","blskey_pop":"R3fdwDhP1Ffhhir5Gns8UPUcBTT5273E3ywWph6kV7c1UxCWj1ihKPA5MBaTEJZeCQsJStn4rpcCCyaqd4d7dW7VSzeguSedb1W2aMM857Lkbf6WZX5GD34HsMfV6BmqFmVCWdx6xiEJLMgtRA1Cn74W7E1yqseCNN33AzShxdzUF1","client_ip":"steward2.default.svc.cluster.local","client_port":"steward2_9702","node_ip":"steward2.default.svc.cluster.local","node_port":"steward2_9701","services":["VALIDATOR"]},"dest":"DeE2fT6oe4BQzqUx1tjD72SySdbRNNBCqJjLrj4BcbAq"},"metadata":{"from":"WLEgXx1KzroBMAwFpvvcWx"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"b69e5fbf21173123d5733231a5e1cbcf53233f2ed08695daefab12dca9092114"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward3","blskey":"QEGoAHv2smPS3747PNntSPQzZCbzwpLdTwZQDnCgDK55DZS9eAHzwkfNcZcGFcM3CRGbbAqQcqsksbhjMTFyaiqaf4FoM8ZaHmxGKrRs2VD7iSqSq3K3ZzLW3TV2iakPvfFQw6rzkwRbgCEiwCXGkt9Mrz73vLvm2x1WixFrwDgyEC","blskey_pop":"RKVQEZFhMoJ2FUiBLzmR8cGabVDXc8xt5KTeaGKpgA2JL9RLRTX1i3DYSAnhDB7Lmr6CLBrxYuADYJbmw2bGLLs9AT3TCEQyfmBv13MUT98SaHk1jxFp42yuQZgCKXyD6EdvDSWvYhpGybiKnMvDSNn4fEkYRY1JT6HzXzHMEDeU7q","client_ip":"steward3.default.svc.cluster.local","client_port":"steward3_9702","node_ip":"steward3.default.svc.cluster.local","node_port":"steward3_9701","services":["VALIDATOR"]},"dest":"Hci99me2FxC7ejLsdE56qXqT4V4Hwe6vfTJTwMDpN4cp"},"metadata":{"from":"BNYqB16U6ELbSxpUqYGxu6"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"f05151122ea0c4c8bdea1ed2bae305bb37934a0c92a566a627abb1d1c9778b9f"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward4","blskey":"3SyMQkfyMawqJec1Bczx6fSdSnkcQWmVgtqDppyaiGdfm21JFK1qV2vGXhcpUeomM5v68bTTzfWPhMepCfXkE8UZJuHxbktgGE9DrSV5ej6oX8jiZ3YASRBpUD1fbcvzb6tW9Z8rSEgkEas4RwsyYojswR23mt6QUH5zgCVGYneA7C9","blskey_pop":"RZbdHp8e7UjPcQUyULEjCetyBC4RnfXkaKGgcfK75KYsxNMe9qF63AVBRPfewggqspB9uaKas2aYaCjxB7cASFL8y9fTngwJhF4ikRUxF8nJiWDkYRRM7wisu85sp8b1DzbJy62w2B2hTNEWQWpfJ7SBCkAuABZ9AzMhpHXTaTJYrb","client_ip":"steward4.default.svc.cluster.local","client_port":"steward4_9702","node_ip":"steward4.default.svc.cluster.local","node_port":"steward4_9701","services":["VALIDATOR"]},"dest":"Ga49A8chvM5DhYoZTXAu5fqxyW8Gf5P4n2DoVZTVhc8c"},"metadata":{"from":"QUUJicdurEobs2wHs2CJum"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"34569ec776a6f8cf766aece248c78fd21f652a08f3f44daae23c9cbc07623601"},"ver":"1"}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  entrypoint.sh: |-
    #!/bin/sh
    {{ if .Release.IsInstall }}
    init_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT > /extdata/$node
    {{ end }}
    
    {{ if .Release.IsUpgrade }}
    cp /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis
    cp /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis
    
    {{- range $inter_node := .Values.nodes }}
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9702/s//${{ upper $inter_node.alias }}_SERVICE_PORT_CLIENT/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9701/s//${{ upper $inter_node.alias }}_SERVICE_PORT_NODE/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    {{- end }}
    start_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT &
    {{ end }}