apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-config
data:
  indy_config.py: |-
    # Current network
    NETWORK_NAME = '{{ .Values.network_name }}'

    # Disable stdout logging
    enableStdOutLogging = False

    # Directory to store ledger.
    LEDGER_DIR = '/var/lib/indy'

    # Directory to store logs.
    LOG_DIR = '/var/log/indy'

    # Directory to store keys.
    KEYS_DIR = '/var/lib/indy'

    # Directory to store genesis transactions files.
    GENESIS_DIR = '/var/lib/indy'

    # Directory to store backups.
    BACKUP_DIR = '/var/lib/indy/backup'

    # Directory to store plugins.
    PLUGINS_DIR = '/var/lib/indy/plugins'

    # Directory to store node info.
    NODE_INFO_DIR = '/var/lib/indy'
  {{- range $node := .Values.nodes }}
  indy.env-{{ $node.alias }}: |-
    NODE_NAME={{ $node.alias }}
    NODE_IP=0.0.0.0
    NODE_PORT={{ $node.node_port }}
    NODE_CLIENT_IP=0.0.0.0
    NODE_CLIENT_PORT={{  $node.client_port }}
    CLIENT_CONNECTIONS_LIMIT=500
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-node-cm-genesis
data:
  domain_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"alias":"trustee1","dest":"NpV5xJd12WExXknMWufG9o","role":"0","verkey":"CtjTBBwXepvdPjkfmAc1X7bEyY1zshQ5cLU7jTbsspYy"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee2","dest":"YU9hx27g9LTTMsaY5QPS3V","role":"0","verkey":"J9mbPMZp5ogoNHKNgwyTgqggnDUcZ37Rog6e79g4LHj4"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee3","dest":"WYnXPY95bjpeqjmDdcCdEq","role":"0","verkey":"H757uazefvxZuWXqV9GfLAovDc3nkXV4PMKUoN51N5Aq"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee4","dest":"NESgiNA2W1jWJNpUkXvL9F","role":"0","verkey":"CaBLUguY5JcP7TkSqjMfjg7zCNwhPdfTFbGZjJ9xj8CK"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee5","dest":"5CbSzSxw8jL3yE64McspYG","role":"0","verkey":"3HmV6eoJ7Q3QgPN8VwcxCEkw818CkN6juHXeCkgf5z4X"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"XvyRKoDMxAqeoXm8PDjdPT","role":"2","verkey":"Hrn1t45bm5C1eb5VqQRZBtYNSvhkS5KoAMbxCtXp2dyv"},"metadata":{"from":"5CbSzSxw8jL3yE64McspYG"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"Pq7y7BJ59ivZbxb1mve4Ti","role":"2","verkey":"DSh3kzbeQfYZZB4DfzYvDYMajzWjc71H21eAMVAWSa6N"},"metadata":{"from":"5CbSzSxw8jL3yE64McspYG"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"6RaNFs5WK6FZofKwqWnwP9","role":"2","verkey":"3xTM1CDo8L54cGJiepezz1UYv3eN3QfobBgXUkC4wcFd"},"metadata":{"from":"5CbSzSxw8jL3yE64McspYG"},"type":"1"},"txnMetadata":{"seqNo":8},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"NCSBUTmHGDMt5ooaKaFamH","role":"2","verkey":"CZ5qZ28uvHf8xDJpmg9GUBVXNCQhCBwuxQFD4E5En3yg"},"metadata":{"from":"5CbSzSxw8jL3yE64McspYG"},"type":"1"},"txnMetadata":{"seqNo":9},"ver":"1"}

  pool_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward1","blskey":"mnazX1osYJ2Tt3YMvyXdoVAQEvwFE6gpxJfkg8guFAokNpWxZ7Ae8DAUnMctWxGjcexFSjUG81jFGHTaCYwuMq2uRd4xY7t8co8CCPNe36NFgYVuiQByqAywRZBpBLbJXo2Nw1j9MxgewKieAQ9NNTWRrnmzuWCevR9jcLLFqKAEUf","blskey_pop":"R4tvD7pQ8hZN3LKYDuU4HR3MpVUqwE1QPCxcvaC33Nhx3L5g6fEA18SR56GN1tkTQd5vMjDhRyHxybWozF2nNkEP1BReyNN7rvpBTCAXg7a1QcznjEAzxN83s64h54JwmBGys9jc7Y2tH8iXBdzVanMczFpioLm7EBtSYVjTtgGww5","client_ip":"steward1.default.svc.cluster.local","client_port":"steward1_9702","node_ip":"steward1.default.svc.cluster.local","node_port":"steward1_9701","services":["VALIDATOR"]},"dest":"C4rvXp3faKKrGnHczAx5P6ELaKYhmy46mSJZfgAbqCmF"},"metadata":{"from":"XvyRKoDMxAqeoXm8PDjdPT"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"d217afd29dd422162e5c528f3fd023397c8469b9e3f00f46835d0e671006f50b"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward2","blskey":"3fZFJbNnZNEtTQsDXMDir4JyXrbNezkr3qTqpgxBjigCjFoNDM4eqdJXdcBkXBjpNuT1DLXnAs4ewiLHJTqtddebVYU8FadffdqQ1LL2YpeUuU7fH59P1dc8W8Y1hxM9CyGov3ZNHKCGF4Fk21NzWP9mELmj5ahSqnNzCtpnrVxHhe6","blskey_pop":"QoSX4PS3nAhHs4gnDnFyeshUPxfD34G1esXBrAnHCQoB8DfrwQ5kQuQ1MohGjcp4wCNWcd2aPPjhJoYjFt1RQEZKX1J9cgLFAyKfTMoNtnvHiNhz38mrHNbMvM2bhAYXQ3xxptRESoBA4HNebtkP8SPQ56VZCJszXKWq2EheYaLoq1","client_ip":"steward2.default.svc.cluster.local","client_port":"steward2_9702","node_ip":"steward2.default.svc.cluster.local","node_port":"steward2_9701","services":["VALIDATOR"]},"dest":"GtHasoVb92jwwRxmWbDATZb8k78bJbJkouWrusK5mQJD"},"metadata":{"from":"Pq7y7BJ59ivZbxb1mve4Ti"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"b69e5fbf21173123d5733231a5e1cbcf53233f2ed08695daefab12dca9092114"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward3","blskey":"N4TN4qqpySm4B5PHxhZdjfDVQ58Jo9wrcuFCYSM6HR2MyVQT4tBdfPCuhEPDTQZcn1Vgt2MNPCJ2VKFx9SZH4WGYSxvGNWs6Uov1U8arsM1wZqeMWvEDB2Ta7X4ghw6tyfTHZWxvhkmeqAvsXjj4PrxNhKTn7wf3vzPBQ8mrRLXPDc","blskey_pop":"RYsrGwgsQsyPiJHocroR2Ki7R2s48E2d3TKsEqhtZrPs1aYo3wj11TEZdBGigXEvBxd6gBANfkwgw8g9NzMsu5oh1tdeiAK5gs5wJnFH6UiCzERABFs6TZUdhgxCZQ9B4FqbLdBu98hU3N7WMkVo245CG9UD7oQhxgvGTv3QcBn5hR","client_ip":"steward3.default.svc.cluster.local","client_port":"steward3_9702","node_ip":"steward3.default.svc.cluster.local","node_port":"steward3_9701","services":["VALIDATOR"]},"dest":"BrvW39H2JCVR7mgFstgeq1RCaAVMGUvfPyhvVFA69XVj"},"metadata":{"from":"6RaNFs5WK6FZofKwqWnwP9"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"f05151122ea0c4c8bdea1ed2bae305bb37934a0c92a566a627abb1d1c9778b9f"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward4","blskey":"FtGVjWt7dg75TEt2UcLsSPttx4UBMmed89copmBwxohTmmJxk6eTNxB9XBbiek7yEM3f8WLgDCTneJoqiyDKRzPfNYpMMY2qCvgzsKSbWLLeRixo2ZGFwyMpxstrn4nkgK4vyu6fhDFrzuBhTN1pZCjWdo9vWzpKpyYAcQAHqvxjaA","blskey_pop":"R2iALhiCCwqB8n63MWHGUbFR7xMZfu1Gb7mShbZ9zQkUc5uQ7dLg53qjgY9698dHhhhE8WuNEPjzWSHBSoexEgyziDm9rgfUTWD4yCZRCwm5yg6puQxrDScgUCHuw6ATBPJreqoMBosTrt9xwTALgVqG6yZwVoGpVPuAdTqJh6eMXD","client_ip":"steward4.default.svc.cluster.local","client_port":"steward4_9702","node_ip":"steward4.default.svc.cluster.local","node_port":"steward4_9701","services":["VALIDATOR"]},"dest":"ATuqLoiHFSTzkQUtRAaK6WTnDxMqPgm7AMMu3svXoyuc"},"metadata":{"from":"NCSBUTmHGDMt5ooaKaFamH"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"34569ec776a6f8cf766aece248c78fd21f652a08f3f44daae23c9cbc07623601"},"ver":"1"}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  entrypoint.sh: |-
    #!/bin/sh
    {{ if .Release.IsInstall }}
    init_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT > /extdata/$node
    {{ end }}
    
    {{ if .Release.IsUpgrade }}
    cp /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis
    cp /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis
    
    {{- range $inter_node := .Values.nodes }}
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9702/s//${{ upper $inter_node.alias }}_SERVICE_PORT_CLIENT/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9701/s//${{ upper $inter_node.alias }}_SERVICE_PORT_NODE/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    {{- end }}
    start_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT &
    {{ end }}