apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-config
data:
  indy_config.py: |-
    # Current network
    NETWORK_NAME = '{{ .Values.network_name }}'

    # Disable stdout logging
    enableStdOutLogging = False

    # Directory to store ledger.
    LEDGER_DIR = '/var/lib/indy'

    # Directory to store logs.
    LOG_DIR = '/var/log/indy'

    # Directory to store keys.
    KEYS_DIR = '/var/lib/indy'

    # Directory to store genesis transactions files.
    GENESIS_DIR = '/var/lib/indy'

    # Directory to store backups.
    BACKUP_DIR = '/var/lib/indy/backup'

    # Directory to store plugins.
    PLUGINS_DIR = '/var/lib/indy/plugins'

    # Directory to store node info.
    NODE_INFO_DIR = '/var/lib/indy'
  {{- range $node := .Values.nodes }}
  indy.env-{{ $node.alias }}: |-
    NODE_NAME={{ $node.alias }}
    NODE_IP=0.0.0.0
    NODE_PORT={{ $node.node_port }}
    NODE_CLIENT_IP=0.0.0.0
    NODE_CLIENT_PORT={{  $node.client_port }}
    CLIENT_CONNECTIONS_LIMIT=500
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-node-cm-genesis
data:
  domain_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"alias":"trustee1","dest":"66MFps554TXtEkHSYPJ9QD","role":"0","verkey":"3mya9hxTM5c1PCiNFt1oTapegiZDrv6phzPnohJUS2Fi"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee2","dest":"Pv9ejhGT9T9mnQBbBpPcso","role":"0","verkey":"DVS2ScipTHASGbkcgz9GNWaMDXnjXGh9sJjNoqgBRAYW"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee3","dest":"NQ3UkTvRj5gnZYwdWuKRog","role":"0","verkey":"CfQopqW6o5TvPuV4SuE61nRz6TvXrBLfwq5LcxEfGcvj"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee4","dest":"PKsTXVDEJHZLwB4DwCsYkf","role":"0","verkey":"DAkPjUwaFLVzNfyBTYTSrcuooeP9Rrw487tMyzaSbQ6B"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee5","dest":"GoGWstXEbZTZ3mCSE5AjWA","role":"0","verkey":"9cQ2HDXqC9qe4FfbJBtvaJdJYHVqH3FVfQAgnUBZTpKZ"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"SGaeXWYcdxKEcs3aubcpSC","role":"2","verkey":"Emnsrh3mwQxemrB1qB3G2SBYk5m1XX1aniPJE4qqAZ7x"},"metadata":{"from":"GoGWstXEbZTZ3mCSE5AjWA"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"3tg2Azmcr7BSWXG67DhWP7","role":"2","verkey":"2aPU4XCnkeL3jXSAU17WMorUD7q1VpjQ7Mai1ELXy6aD"},"metadata":{"from":"GoGWstXEbZTZ3mCSE5AjWA"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"GdSEE8H2eoBvt87gyaF8ZM","role":"2","verkey":"9X3CP4yFYkJBgTCXZpBGLpV1XsJyJeLUk7aUTHttzrvX"},"metadata":{"from":"GoGWstXEbZTZ3mCSE5AjWA"},"type":"1"},"txnMetadata":{"seqNo":8},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"B7CWTb9oBiJaSHU1BbjyEw","role":"2","verkey":"6WVtUKW4mPhPSRAkztVAC5a5uwg6SLoEe8iggNdB7qPk"},"metadata":{"from":"GoGWstXEbZTZ3mCSE5AjWA"},"type":"1"},"txnMetadata":{"seqNo":9},"ver":"1"}

  pool_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward1","blskey":"3HzPqURuPuGxzm8ZdDvpXAyX4t8EtH3HttwYSJ9YFCTmyDK4RX8KEuqn8k7F6zumBmXoNk3AQY8vQBMYc7hSnKrG38k3yFmjEv2xSF6ExzY9JHRVApzL8to7UFnMc8P2zXeGGw39csBLEM9fx4f3W2s31AWzr2fbhGGZfHmo1Y86zJV","blskey_pop":"RXbUYyNhuYk1sSt5XANMxXabXX4nauw5SPX6EESmS64Wu5khQyFyiQ6ybk6eswXRoCtLubLd78VgeUmPKc9FpTr5p39wiNuwXzdcSXhgiPwUVgjZU66nqxehouGjHEyzpb4S1oTmuSJ7w75CQq35caR6cew2gR9oiFxwiu8MJ7uW2K","client_ip":"steward1.default.svc.cluster.local","client_port":"steward1_9702","node_ip":"steward1.default.svc.cluster.local","node_port":"steward1_9701","services":["VALIDATOR"]},"dest":"FCsu6GQ5tmya43pPhuynQGfZUZtyGwg6PEVTuyWiS7Pv"},"metadata":{"from":"SGaeXWYcdxKEcs3aubcpSC"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"d217afd29dd422162e5c528f3fd023397c8469b9e3f00f46835d0e671006f50b"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward2","blskey":"phKk1itmnitkwXaZnXud8wsHJcQUCpEMYnCfyrP6YvHgbpPwiwH3ZvCvsTXdRxyHkBR6NAPkKNJYKiCASYPbbPERMoEsCQUozM73moao22y2HYHrdD6KuEZmNjWHfiw5aY3kN3CwnZLQL12bCuHBmR7okMCrGrEJCbq6wZ54PH3czq","blskey_pop":"QsRM8po7UYVXUsCpaQaKpdcLXHfsfTxrfjevWUUBcJuF4bQYzSPeeTQ6gNjF8zaiQhmrdwLW1Lz88X1UsNFWEp7dQJxn7hHZ8HU5Vdt9CVRDtTxC5ZJDhL7pLdWXDQaK7XE5tSpa3RfLkaE3nUuDRAg9qYNY2JAB88iNyHbygwTqR1","client_ip":"steward2.default.svc.cluster.local","client_port":"steward2_9702","node_ip":"steward2.default.svc.cluster.local","node_port":"steward2_9701","services":["VALIDATOR"]},"dest":"FQBh3vKdPwuxR6em4dqjtBVkQKjS5r7or41LSafbWfya"},"metadata":{"from":"3tg2Azmcr7BSWXG67DhWP7"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"b69e5fbf21173123d5733231a5e1cbcf53233f2ed08695daefab12dca9092114"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward3","blskey":"3XAguTXdLEvhTxGzqqFPnaXLPy9kwgSnR5tL65xQVYtGG2pCCXxGw1i7ArWQyRiXbjZgwR6tLK2TAcFMszFGxE3PeVazK7RdhwF3YaoREhPXVvDcVSXoVnTxkLTdA8TxvX68A9FZSG5N2rRm3mhyRnEoaFma8A9DzndYcnkwFC6syfC","blskey_pop":"Qr738DQUYJ7tAgS4S8M5J8eNZup3tLauyWgcyVyGdBNDakby5u1PhrPPbcc6PRVazSksoMy8R6wTRat8wFhh6NjqjQMPFkZ9tugHtjUKDnW4WQfDNFjjKtza9QuyZaHpkp5iHYv4jeFq7Ljtxbd4gc2WF5b2ubqhDGnLhskzMnrQTh","client_ip":"steward3.default.svc.cluster.local","client_port":"steward3_9702","node_ip":"steward3.default.svc.cluster.local","node_port":"steward3_9701","services":["VALIDATOR"]},"dest":"3x6xXR89rcWa2iKW6VJybuZXt2vDSs2iPZwqDXwtdNtc"},"metadata":{"from":"GdSEE8H2eoBvt87gyaF8ZM"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"f05151122ea0c4c8bdea1ed2bae305bb37934a0c92a566a627abb1d1c9778b9f"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward4","blskey":"2ijvhGCtr2kzmPBWyUnd4B78F1e84aYYfT4a51RJNWUEb2yui4QFBkiVmj9g8uNrxyAWEer2Axg98XWiJUL9ZhEZ526o8aw8EkxUTJnemjg8ZBJHnnQ85hTTLpiDQTivSGXbhoweLebYFtK4u7xFoK3jN3mqqe68ApXxNq1DUsjRTkR","blskey_pop":"RWAH4MRFYUotmtbzbghTRb57hpLLMVUhcF9drog9UXWGK5Uu2aFi5vxwb9671ePkhZXzqByf2fq3iDJToyvbbZzHuQLjy1MZGdNJwrpwQS2s58jR8Rnc1m3owFUafV46RASnbDDwjZwzdjYHjFEMhy8K3DfwUeh9iKevtVBqCEV7AF","client_ip":"steward4.default.svc.cluster.local","client_port":"steward4_9702","node_ip":"steward4.default.svc.cluster.local","node_port":"steward4_9701","services":["VALIDATOR"]},"dest":"89NBnRfWXQsfssQs1DByXGBSyFJeFZ3wqa8zbeXeDfCW"},"metadata":{"from":"B7CWTb9oBiJaSHU1BbjyEw"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"34569ec776a6f8cf766aece248c78fd21f652a08f3f44daae23c9cbc07623601"},"ver":"1"}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  entrypoint.sh: |-
    #!/bin/sh
    {{ if .Release.IsInstall }}
    init_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT > /extdata/$node
    {{ end }}
    
    {{ if .Release.IsUpgrade }}
    cp /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis
    cp /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis
    
    {{- range $inter_node := .Values.nodes }}
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9702/s//${{ upper $inter_node.alias }}_SERVICE_PORT_CLIENT/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9701/s//${{ upper $inter_node.alias }}_SERVICE_PORT_NODE/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    {{- end }}
    start_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT &
    {{ end }}

    sh -c tail -f /dev/null