apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-config
data:
  indy_config.py: |-
    # Current network
    NETWORK_NAME = '{{ .Values.network_name }}'

    # Disable stdout logging
    enableStdOutLogging = False

    # Directory to store ledger.
    LEDGER_DIR = '/var/lib/indy'

    # Directory to store logs.
    LOG_DIR = '/var/log/indy'

    # Directory to store keys.
    KEYS_DIR = '/var/lib/indy'

    # Directory to store genesis transactions files.
    GENESIS_DIR = '/var/lib/indy'

    # Directory to store backups.
    BACKUP_DIR = '/var/lib/indy/backup'

    # Directory to store plugins.
    PLUGINS_DIR = '/var/lib/indy/plugins'

    # Directory to store node info.
    NODE_INFO_DIR = '/var/lib/indy'
  {{- range $node := .Values.nodes }}
  indy.env-{{ $node.alias }}: |-
    NODE_NAME={{ $node.alias }}
    NODE_IP=0.0.0.0
    NODE_PORT={{ $node.node_port }}
    NODE_CLIENT_IP=0.0.0.0
    NODE_CLIENT_PORT={{  $node.client_port }}
    CLIENT_CONNECTIONS_LIMIT=500
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-node-cm-genesis
data:
  domain_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"alias":"trustee1","dest":"CLPb34ieUBvMNDdijvDwsz","role":"0","verkey":"7BJNo9LCgEVK8soFJjhwLUaxRQFJrTmHetjj8JF6ffzy"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee2","dest":"LdGqHFwG1HhLDqtPJpXycH","role":"0","verkey":"BhQ446ZP4jZL9na83ZfkB9phwnwEd9Q9g4JG2ucPthER"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee3","dest":"8HLuUFk21CTdG1aWLm3Eo4","role":"0","verkey":"4yC6qYeNk2AqA3Qj7WwWVQ57eiyvCz6sTkcmdRa7h8Gq"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee4","dest":"VEzTmeT94g53FZCphNU6r7","role":"0","verkey":"GPm7i4w1Yjiy4RSUzQW3dF44Whc14dKSpVKWKXfzPLSw"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"alias":"trustee5","dest":"P1kmrJwwNXCNNfLhVDmCtz","role":"0","verkey":"CzsjYCsQQR53EXEmDs7NGTYXbMRVkpoXbxnhz9ywRZpk"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"SSBu9vU6BXxo8NY2pdz4VX","role":"2","verkey":"Es2bhTCaFQMi5c9AhvadQpLsUwEEHBkd9Pf25Yp9UXPu"},"metadata":{"from":"P1kmrJwwNXCNNfLhVDmCtz"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"TX9FgqrCDGjeEgM6zsaLAr","role":"2","verkey":"FTLiCP5ax7YohqDrXeQdnrf9h8Qu5rxzJth8L3fUWjHd"},"metadata":{"from":"P1kmrJwwNXCNNfLhVDmCtz"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"5nPA2kQE6t9kVU1aQbmAWA","role":"2","verkey":"3cBbKQjxusoRmitmZXArKDD8Y6Jw7pmJEhVLpncTUfwp"},"metadata":{"from":"P1kmrJwwNXCNNfLhVDmCtz"},"type":"1"},"txnMetadata":{"seqNo":8},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"dest":"JXt4ZJX1pnZz9gRX2VhBFG","role":"2","verkey":"AZEbQ9RyxE66D3HC9zxTmd2qLTGPduFKbNzJaFSQhffK"},"metadata":{"from":"P1kmrJwwNXCNNfLhVDmCtz"},"type":"1"},"txnMetadata":{"seqNo":9},"ver":"1"}

  pool_transactions_genesis: |-
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward1","blskey":"23r4UVDYd5rdD5rsbDf5Nhm2mP6ZT9ZEDoz2YgurJYF8y4PUtW1hixdjKdm3KuoHEH19jULkRnD9QRxd3dB8NA6qpXzjkyembqHtc22EkFsuYN37wj8Ft2kDDCU8DA7ZvY3UnnHowJ7MNfxJAmQXJepb3oNZbPdjFUrNPimbaytUSLM","blskey_pop":"RD7LF4gSdakx2rehDXowEA1EE8Y34WNBDfghQfXVqRfBENeyDqkBiPJYj9pmwrcSNqnqqEsTgpM4hw7McCqX2JqRLwAKnaWAviBYgAjD7i1P9NPY4WjAWcwYFWGh8guSbpBvMzUnfErG2K2FxbkBFmz9Esfs2FAq4AyRphn82d1GyM","client_ip":"steward1.default.svc.cluster.local","client_port":"steward1_9702","node_ip":"steward1.default.svc.cluster.local","node_port":"steward1_9701","services":["VALIDATOR"]},"dest":"6MsSatxEYW47ZbtLyGK2oTeRX4JDdVnT5zs8ccaqxxGa"},"metadata":{"from":"SSBu9vU6BXxo8NY2pdz4VX"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"d217afd29dd422162e5c528f3fd023397c8469b9e3f00f46835d0e671006f50b"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward2","blskey":"4gyjHvh4VTke7tFg9beQRUaKrmg8MQdEZ4vZvN45zHFxoveLoWhAvnehjRzYftTmNYJfkv5srqzmhqkm9dLsWusQ8qdATLA4fzRkxy2PyrePqDgbV4JHRZaWhxnZQQY9DejovkVMrTzS3NdGqbQrENj1JHnDgXbmkFFyGY72Ph12w3y","blskey_pop":"RWxr5mJxzznKhcFM2vcPaCUHMCN6SzgYH3ksTqteB57sFLa6bcau8A5MHoem5gzYrans7SZj96oUFLZHegMqBWkn437GwTcqPTGszXfChTw679q5EeS7vQt2YhYHMHe1d14U7cmPqmUu5zYE4cdeADBdZuZkmfB6z4ZS84gM928Bc3","client_ip":"steward2.default.svc.cluster.local","client_port":"steward2_9702","node_ip":"steward2.default.svc.cluster.local","node_port":"steward2_9701","services":["VALIDATOR"]},"dest":"xcZxQPb4brZnktLACY4TJrUu3QmnQjNrQEusZjWX4r4"},"metadata":{"from":"TX9FgqrCDGjeEgM6zsaLAr"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"b69e5fbf21173123d5733231a5e1cbcf53233f2ed08695daefab12dca9092114"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward3","blskey":"tFx1XAp7jpFTmfNfRKrkBBA65ZsP52bA1ptKGL4yAdPWKKTbcQBN5121nSUTrQF4qpBT3Hicxhob4MxuyHxbEJwyJ6QmPpr3z7aZwKcHhofe3h9f71mELxaNzviSzbZRW1FoTr3gQ8XDwQhsjDXFD2D579pW3F8Zk9csemPU8avrXV","blskey_pop":"RUYZWDepV9mhUnmRuMXHraHoYkNQDm7GTchAGMYwdy15j3EnPKEETYgKHkcUupcjN87vZGoDBksn62EKJiuwRZE7KEXEXX6xBUffTvVgjvPmQxVpN3PVte6bZ98tfs4WQ6CAUz7PohA683FVB5BjRPX5w6mekVcfMmqttfzxhdThNF","client_ip":"steward3.default.svc.cluster.local","client_port":"steward3_9702","node_ip":"steward3.default.svc.cluster.local","node_port":"steward3_9701","services":["VALIDATOR"]},"dest":"3gT5DX8bkeSFgpGNxwUJctuNDZAwKqkz4PYQBWVmcPFx"},"metadata":{"from":"5nPA2kQE6t9kVU1aQbmAWA"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"f05151122ea0c4c8bdea1ed2bae305bb37934a0c92a566a627abb1d1c9778b9f"},"ver":"1"}
    {"reqSignature":{},"txn":{"data":{"data":{"alias":"steward4","blskey":"ua8UKfqMTAD1L2Pq6tULGmjxMeJLzoNAYT7TrHuPFrGzmzdhKK2zfhggmyNhaBNMDCuhqPXZvV4Lazg7znooTvqeZvKpdGHb64T8EYe4qnnSAfc3xc5fLoneUQJotH9roXokACdQfcWdpGy32eRb1d1SUpFqPxDHB9CDhWqzM2E1Xp","blskey_pop":"QnRcbXuWVoKUJaRab79A9PVnFD3aQM5pP4FzPwSzd4qaSnqGfVHdzgz6NaPG2JwjBfZsrpfUh1BamNJFy5uk6ws5m1Qsh3EqRaMi6mRMedyk474VPTMTsLRysiUYbBoK7uu45JBEYuVP5bi62vdkN7ZUcQLiNvc79XFjqrfACpGf27","client_ip":"steward4.default.svc.cluster.local","client_port":"steward4_9702","node_ip":"steward4.default.svc.cluster.local","node_port":"steward4_9701","services":["VALIDATOR"]},"dest":"H9mKFdCiJnjXXGgupkp6CJqDBpz2YHir1DQDxujDqrA8"},"metadata":{"from":"JXt4ZJX1pnZz9gRX2VhBFG"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"34569ec776a6f8cf766aece248c78fd21f652a08f3f44daae23c9cbc07623601"},"ver":"1"}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  entrypoint.sh: |-
    #!/bin/sh
    {{ if .Release.IsInstall }}
    init_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT > /extdata/$node
    {{ end }}
    
    {{ if .Release.IsUpgrade }}
    cp /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/pool_transactions_genesis
    cp /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis_readonly /var/lib/indy/{{ .Values.network_name }}/domain_transactions_genesis
    
    {{- range $inter_node := .Values.nodes }}
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9702/s//${{ upper $inter_node.alias }}_SERVICE_PORT_CLIENT/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}.default.svc.cluster.local/s//${{ upper $inter_node.alias }}_SERVICE_HOST/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    sed -i "0,/{{ $inter_node.alias }}_9701/s//${{ upper $inter_node.alias }}_SERVICE_PORT_NODE/" /var/lib/indy/{{ $.Values.network_name }}/pool_transactions_genesis
    {{- end }}
    start_indy_node $node 0.0.0.0 $C_NODE_PORT 0.0.0.0 $C_CLIENT_PORT &
    {{ end }}