
{{- range $node := .Values.nodes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $node.alias }}
spec:
  externalIPs:
    - 192.168.1.112
  ports:
  - port: {{ $node.node_port }}
    name: node
  - port: {{ $node.client_port }}
    name: client
  # clusterIP: None
  selector:
    app: {{ $node.alias }}-{{ $.Release.Revision }}
{{- end }}